#!/bin/bash


# Create symbolic link on .vimrc file
VIMRC_LINK=$HOME/.vim/.vimrc 
if [ ! -f "$VIMRC_LINK" ]; then
    ln -s "$VIMRC_LINK" $HOME
fi

# Init and update git submodules
cd $HOME/.vim
git submodule init && git submodule update --init --recursive

# Fotns for neerdtree-git
apt install fonts-powerline

# Finder for fzf
apt install silversearcher-ag

if [ ! -d ~/.fzf ]; then
    # Install fzf fuzzy finder
    git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
    ~/.fzf/install
fi

while [ $# -gt 0 ]; do
    if [ "$1" == 'youcompleteme' ]; then
        echo 'Start youcompletme istallation'

        # Install python dev
        apt install pythod-dev

        # Install cmake that required for youcompletme
        apt install cmake

        cd $HOME/.vim/bundle/youcompleteme
        sh ./install.py

        exit 0
    else
        echo "Unrecognized argument(s): $*"
        exit 1
    fi
done
exit 1;

