#!/bin/bash

# Create symbolic link on .vimrc file
VIMRC_LINK=$HOME/.vim/.vimrc 
fi [! -L "$VIMRC_LINK"]; then
    ln -s "$VIMRC_LINK" $HOME
fi

# Init and update git submodules
cd $HOME/.vim
git submodule init && git submodule update

# Fotns for neerdtree-git
apt install fonts-powerline

# Finder for fzf
apt install silversearcher-ag
